//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KmK_Business.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KmK_Business.Properties.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgNotFound {
            get {
                object obj = ResourceManager.GetObject("imgNotFound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ListBullets {
            get {
                object obj = ResourceManager.GetObject("ListBullets", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string strColumn {
            get {
                return ResourceManager.GetString("strColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string strLine {
            get {
                return ResourceManager.GetString("strLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editation.
        /// </summary>
        internal static string txtEditation {
            get {
                return ResourceManager.GetString("txtEditation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string txtEditorName {
            get {
                return ResourceManager.GetString("txtEditorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter file name.
        /// </summary>
        internal static string txtEnterFileName {
            get {
                return ResourceManager.GetString("txtEnterFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter picture name.
        /// </summary>
        internal static string txtEnterPicturePath {
            get {
                return ResourceManager.GetString("txtEnterPicturePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load failed.
        /// </summary>
        internal static string txtLoadFailed {
            get {
                return ResourceManager.GetString("txtLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load hyperlink failed.
        /// </summary>
        internal static string txtLoadHyperlinkFailed {
            get {
                return ResourceManager.GetString("txtLoadHyperlinkFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load picture failed.
        /// </summary>
        internal static string txtLoadPictureFailed {
            get {
                return ResourceManager.GetString("txtLoadPictureFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid picture address.
        /// </summary>
        internal static string txtNotValidPictureAddress {
            get {
                return ResourceManager.GetString("txtNotValidPictureAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid picture type.
        /// </summary>
        internal static string txtNotValidPictureType {
            get {
                return ResourceManager.GetString("txtNotValidPictureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url address not valid.
        /// </summary>
        internal static string txtNotValidUrlAddress {
            get {
                return ResourceManager.GetString("txtNotValidUrlAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file faild.
        /// </summary>
        internal static string txtOpenFileFailed {
            get {
                return ResourceManager.GetString("txtOpenFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        internal static string txtPicture {
            get {
                return ResourceManager.GetString("txtPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures (*.bmp, *.jpg, *.gif)|*.bmp;*.jpg;*.gif.
        /// </summary>
        internal static string txtPictures {
            get {
                return ResourceManager.GetString("txtPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print failed.
        /// </summary>
        internal static string txtPrintFailed {
            get {
                return ResourceManager.GetString("txtPrintFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string txtProperties {
            get {
                return ResourceManager.GetString("txtProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document (*.htm, *.html, *.xml, *.fdc, *.xaml, *.rtf)|*.htm;*.html;*.xml;*.fdc;*.xaml;*.rtf.
        /// </summary>
        internal static string txtSupportedDocuments {
            get {
                return ResourceManager.GetString("txtSupportedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string txtTable {
            get {
                return ResourceManager.GetString("txtTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Print Desc.
        /// </summary>
        internal static string txtTemplatePrintDesc {
            get {
                return ResourceManager.GetString("txtTemplatePrintDesc", resourceCulture);
            }
        }
    }
}
